# Generated by Django 6.0.5 on 2026-05-24 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comedian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(blank=True, max_length=200, null=True)),
                ('portfolio_url', models.URLField(blank=True, null=True)),
                ('fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('experience', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'comedian',
            },
        ),
        migrations.CreateModel(
            name='EventStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_title', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'event_statuses',
            },
        ),
        migrations.CreateModel(
            name='PerformanceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_title', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'performance_statuses',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('capacity', models.IntegerField()),
            ],
            options={
                'db_table': 'place',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='TicketStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_title', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ticket_statuses',
            },
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_title', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'user_statuses',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('date_time', models.DateTimeField()),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_participants', models.IntegerField()),
                ('duration_minutes', models.IntegerField()),
                ('id_status_event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_v1.eventstatus')),
                ('id_place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_v1.place')),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_order', models.IntegerField()),
                ('duration_minutes', models.IntegerField()),
                ('id_comedian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v1.comedian')),
                ('id_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v1.event')),
                ('id_status_perf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_v1.performancestatus')),
            ],
            options={
                'db_table': 'performance',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('login', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('id_role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_v1.role')),
                ('id_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_v1.userstatus')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_code', models.CharField(max_length=100, unique=True)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('id_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v1.event')),
                ('id_status_ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_v1.ticketstatus')),
                ('id_viewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_v1.user')),
            ],
            options={
                'db_table': 'ticket',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('id_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v1.event')),
                ('id_viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_v1.user')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='id_organizer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_events', to='api_v1.user'),
        ),
        migrations.AddField(
            model_name='comedian',
            name='id_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_v1.user'),
        ),
    ]
